# Generated by Django 4.2.5 on 2023-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='contato',
            field=models.CharField(max_length=9),
        ),
    ]
